"""empty message

Revision ID: 351f90005eb4
Revises: 252a58498945
Create Date: 2018-07-27 10:55:12.281651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351f90005eb4'
down_revision = '252a58498945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
